title:              Sarrah's Blogs
email:              sarrahbastaw@gmail.com
description:        A Place for me to blog about anything and everything in my tech career
author:             Sarrah Bastawala
baseurl:            "/blogs"
url:                "https://sarrah-basta.github.io/"

# Social Profiles
twitter_username:
github_username:    sarrah-basta
facebook_username:
instagram_username: sarrahb__ 
linkedin_username: sarrah-bastawala

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

theme: jekyll-theme-minimal